### ISSUE TITLE
Web browsers =! WebUSB

### ISSUE THREAD

**Issue by MrSVCD** [shilga/croco-cartridge-webapp#1]
Hi
On your online webapp could you add a link to the download version if you detect that the web browser don't support webusb?
Something like "Use another browser that support WebUSB or download a stand alone version here: https://github.com/shilga/croco-cartridge-webapp/releases"
Best Regards
MrSVCD

**Comment by shilga** [comment]
That is a good idea.

**Comment by shilga** [comment]
Implemented in https://github.com/shilga/croco-cartridge-webapp/releases/tag/v0.7.1

**Comment by MrSVCD** [comment]
The link points to the wrong address:
https://github.com/shilga/rp2040-gameboy-cartridge-firmware/releases
Should probably be:
https://github.com/shilga/croco-cartridge-webapp/releases

**Comment by shilga** [comment]
Dooh... I'm an idiot sometimes...
